development:
  adapter: postgresql
  database: opencurriculum_development

test:
  adapter: postgresql
  database: opencurriculum_test

development:
  adapter: postgresql
  database: opencurriculum_development
